---
title: "Model 1"
output:
  pdf_document: default
---

```{r setup}
library('rjags')
library(dplyr)
library(tibble)
library(stringr)
library(ggplot2)
library(tidyr)

output_folder = "../data/models/v1/"
save_output   = TRUE
if (save_output) dir.create(output_folder, recursive = TRUE, showWarnings = FALSE)
```

### Preprocess

#### Load data

Loading data in as a wide data frame

With \~ rows (regions) x columns (weeks)

1st column is the region names

```{r}
uecDf    = read.csv('../data/wide_weekly_scaledPer10k.csv')
regions  = uecDf$Region # saving region names
n.region = length(uecDf$Region) # number of regions
uecDf    = uecDf %>% select(-Region) # remove region col
n.weeks  = length(names(uecDf))
head(uecDf)
```

#### Reformat Dataframe to Matrix

Formatting as matrix with \~ rows (regions) x columns (weeks)

```{r}
uecMat = as.matrix(uecDf)
```

### Model 1 Specification

```{r fit}
model =
"
model{
  # Iterate through the regions
  for(i in 1:I){
    #------------
    #Likelihood
    #------------
    # Set first data point in region i to normal
    y[i,1] ~ dnorm(mu[i,1], tau[i])
    # Set second on data points to the AR1 model with a mean with a seasonal component
    for(t in 2:T){
      y[i,t] ~ dnorm(mu[i,t] +
      (phi * (y[i,t-1] - mu[i,t-1])), tau[i])
    }
    # Assign mean to each time point
    # Beta  ~ cosine coeffecient scaler
    # Gamma ~ sine coeffecient scaler
    for(t in 1:T){
      mu[i,t] <- alpha[i] +
                 beta[i]  * cos((2 * pi) * (t/52)) +
                 gamma[i] * sin((2 * pi) * (t/52))
    }
    #Full conditional  mean used in the likelihood
    fullmod[i,1] <- mu[i,1]
    for(t in 2:T){
      fullmod[i,t] <- mu[i,t] + phi * (y[i,t-1] - mu[i,t-1])
    }
    #Residuals
    for(t in 1:T){
      resid[i,t] <- y[i,t] - fullmod[i,t]
    }
    #------------
    #Uninformative Priors
    #------------
    alpha[i] ~ dnorm(0, 0.001)
    beta[i]  ~ dnorm(0, 0.001)
    gamma[i] ~ dnorm(0, 0.001)
    tau[i]   ~ dgamma(0.001, 0.001)
  }
  phi ~ dunif(-1, 1)
}
"

v1_jags_model = jags.model(
  textConnection(model),
  list(
    y  = uecMat,
    I  = n.region,
    T  = n.weeks,
    pi = pi
  ),
  n.chains = 4
)

update(v1_jags_model, n.iter = 10000)

model_parameters = c("alpha", "beta", "gamma", "tau", "phi")

v1_sim = coda.samples(
  model = v1_jags_model,
  variable.names = model_parameters,
  n.iter = 20000
)
```
#### DIC

```{r}
dic_v1 = dic.samples(v1_jags_model, n.iter = 20000)
dic_v1
df_dic = data.frame(
  deviance = sum(dic_v1$deviance),
  penalty  = sum(dic_v1$penalty),
  DIC      = sum(dic_v1$deviance) + sum(dic_v1$penalty)
)
if (save_output) write.csv(df_dic, paste0(output_folder, "dic.csv"), row.names = FALSE)
```

#### Gelman Rubin Statistic

```{r}
gelman_results = gelman.diag(v1_sim, multivariate = FALSE)
gelman_results

if (save_output) {
  write.csv(
    as.data.frame(gelman_results$psrf) %>% rownames_to_column("param"),
    paste0(output_folder, "gelman.csv"),
    row.names = FALSE
  )
}
```

#### Save raw values w/o residuals

```{r}
if (save_output) {
  samples_with_chain = do.call(rbind, lapply(seq_along(v1_sim), function(ch) {
    df = as.data.frame(v1_sim[[ch]])
    df$chain = ch
    df
  }))
  write.csv(samples_with_chain,
            paste0(output_folder, "raw_samples.csv"),
            row.names = FALSE)
}
```
